apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme
spec:
  encryptedData:
    token: AgBqlHe1bn+ksVvuQM5HqkJwtnTP8eaYieNcf6pCxRXO0TM8AQb8KHpyr0WRyGAETwrrtUOsFKEkZmRnCSEzFUwvxO2w86E5Dk8gJgTj5hboczHuCZ0hGyIDJqTPqYwtEuHBpNy0/XBruo5lAgWKzHdeTQHtnCpHhKCgJrM+9/rscAwCjLVrnnmVpIZMZUO0AOm3mNvNFhpP8hSNOR5226DSEg/RXe3N0EhS9RjiqJ36VxS/Ik4GzPBLYOWXSvjTEFOSWOougYJKsZW/BlkCR+2tgoGeGCcquN+kSZpk9MdEKYIsBTLxDYZVcxTC2J3NA3qyadevxXp54PWj3QJDQ5YwZy4yRlwz9+1sVWbpDASs6iyjJEkjhVZe9AhKeB6SyJqXto/54bDQhn8OfJBe7Jewnrjw9xNVf48vcTMj11Arqy1hPD8vu67Q/YgO4Y8z1oJINrvPynnegG853KoIfi129+bYpKHzQSnPRAoz+v/L9Wz7aQYcDPTNg0mGBls0fYETBvSuQVqyzp3lOaQvBHG6ULTA5Qw08XhPWKSOMKcAtVaknxsRpHCp6jEYMJiJDCzLgmpYvmA/CFyOcSAe2HWvjunm9hQR5wx5Lyk81mb9aQFu7bqE1HNbKPBazzqMLoig32By7iUxOeybUCt/34TxI8ZfIaXjdPSVR7oDN1d9/V+Xw/hTElfm+6UJkWMiR0WPPYU9Qbaqsq5V36imeGlTH0TGx2Kvhk0XweS8j6MGENY9GfIk9oSY
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme

